require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/battles", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Battle. As you add validations to Battle, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Battle.create! valid_attributes
      get battles_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      battle = Battle.create! valid_attributes
      get battle_url(battle)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_battle_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      battle = Battle.create! valid_attributes
      get edit_battle_url(battle)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Battle" do
        expect {
          post battles_url, params: { battle: valid_attributes }
        }.to change(Battle, :count).by(1)
      end

      it "redirects to the created battle" do
        post battles_url, params: { battle: valid_attributes }
        expect(response).to redirect_to(battle_url(Battle.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Battle" do
        expect {
          post battles_url, params: { battle: invalid_attributes }
        }.to change(Battle, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post battles_url, params: { battle: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested battle" do
        battle = Battle.create! valid_attributes
        patch battle_url(battle), params: { battle: new_attributes }
        battle.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the battle" do
        battle = Battle.create! valid_attributes
        patch battle_url(battle), params: { battle: new_attributes }
        battle.reload
        expect(response).to redirect_to(battle_url(battle))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        battle = Battle.create! valid_attributes
        patch battle_url(battle), params: { battle: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested battle" do
      battle = Battle.create! valid_attributes
      expect {
        delete battle_url(battle)
      }.to change(Battle, :count).by(-1)
    end

    it "redirects to the battles list" do
      battle = Battle.create! valid_attributes
      delete battle_url(battle)
      expect(response).to redirect_to(battles_url)
    end
  end
end
